return {
	["K-Theory"] = { "mathematics", "algebra", "analysis", "k-theory" },
	["complex analysis"] = { "mathematics", "analysis", "complex_analysis" },
	["philosophy of mathematics"] = { "mathematics", "philosophy" },
	["differential geometry"] = { "mathematics", "geometry", "differential_geometry", "riemannian_geometry", "sympletic geometry" },
	["history of mathematics"] = { "mathematics", "history" },
	["lie theory"] = { "mathematics", "algebra", "differential_geometry", "lie_theory" },
	["anabelian_geometry"] = { "mathematics", "algebra", "number_theory", "anabelian_geometry" },
	["number theory (nt)"] = { "mathematics", "algebra", "number_theory" },
	["riemannian geometry"] = { "mathematics", "geometry", "differential_geometry", "riemannian_geometry" },
	["homotopy_theory"] = { "mathematics", "algebra", "algebraic_topology", "homotopy_theory" },
	["etale"] = { "mathematics", "algebra", "algebraic geometry", "geometry", "algebraic_topology", "etale", "homotopy_theory" },
	["algebraic geometry"] = { "mathematics", "algebra", "algebraic geometry", "geometry" },
	["set theory"] = { "mathematics", "foundations", "set_theory" },
	["logic"] = { "mathematics", "foundations", "logic" },
	["PDE's"] = { "mathematics", "analysis", "differential_equations", "PDE" },
	["analysis"] = { "mathematics", "analysis" },
	["commutative_algebra"] = { "mathematics", "algebra", "commutative_algebra" },
	["elliptic curves"] = { "mathematics", "algebra", "number_theory", "curves", "elliptic_curves" },
	["probability theory"] = { "mathematics", "probability", "statistics" },
	["linear algebra"] = { "mathematics", "algebra", "linear_algebra" },
	["symplectic geometry"] = { "mathematics", "geometry", "symplectic_geometry" },
	["category theory"] = { "mathematics", "algebra", "category_theory" },
	["AI"] = { "AI", "mathematics", "linear_algebra", "transformers", "research" },
	["algebraic topology"] = { "mathematics", "topology", "algebra", "algebraic_topology" },
	["topology"] = { "mathematics", "topology" },
}
