
return {
	-- --to add plugins that are compatible with nvim-cmp (until they presumably migrate)
	-- {
	-- 	"saghen/blink.compat",
	-- 	-- use the latest release, via version = '*', if you also use the latest release for blink.cmp
	-- 	version = "*",
	-- 	-- lazy.nvim will automatically load the plugin when it's required by blink.cmp
	-- 	-- lazy = true,
	-- 	-- make sure to set opts so that lazy.nvim calls blink.compat's setup
	-- 	opts = {},
	-- },
	-- {
	-- 	"saghen/blink.cmp",
	-- 	-- optional: provides snippets for the snippet source
	-- 	dependencies = {
	-- 		"L3MON4D3/LuaSnip",
	-- 		"leiserfg/blink_luasnip",
	-- 		"micangl/cmp-vimtex",
	-- 		"saghen/blink.compat",
	-- 		"ribru17/blink-cmp-spell",
	-- 		"folke/lazydev.nvim",
	-- 	},
	-- 	event = { "InsertEnter", "CmdlineEnter" },
	--
	-- 	-- use a release tag to download pre-built binaries
	-- 	version = "1.*",
	-- 	-- AND/OR build from source, requires nightly: https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust
	-- 	-- build = 'cargo build --release',
	-- 	-- If you use nix, you can build from source using latest nightly rust with:
	-- 	-- build = 'nix run .#build-plugin',
	--
	-- 	config = function()
	-- 		require("configs.blink")
	-- 	end,
	-- 	-- opts_extend = { "sources.default" }
	-- },
}
